services:
  frontend:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true