services:
  frontend_app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.prod
    container_name: frontend_app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:80"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge