version: '3.8'

services:
  frontend_app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.prod
    container_name: frontend_app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:80"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network
    labels:
      # Labels para nginx-proxy-manager
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  frontend-network:
    driver: bridge