version: '3.8'

services:
  frontend:
    image: ghcr.io/univesp-pi-2/frontend:latest
    container_name: prod-front-app
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - prod-network-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  prod-network-app:
    external: true
